spring:
  datasource:
    url: jdbc:h2:mem:awscrud;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 80

jwt:
  secret-key: YXdzY3J1ZC1qd3Qtc2VjcmV0LWtleS1mb3ItZGV2LXVzZS1vbmx5LTEyMzQ1Njc4OTA=
  access-exp: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
